"""Extract solicitor answers from a PDF generated by the Uplift Collator web app.

The PDF structure is produced by ``generatePdfSummary`` in ``script.js`` via
helpers ``addSectionHeader`` (renders UPPERCASE titles), ``addDetail`` (renders
``Label:  Value``) and ``addCriterion`` (renders three lines per ticked item:
bullet+label, category, ``Explanation: ...``). We parse against that structure.

Output shape mirrors the in-app ``formData``::

    {
      "caseDetails": {"feeEarnerName": ..., "matterType": ..., "caseMatterName": ...},
      "panelMembership": {key: {"checked": True, "label": ...}, ...},
      "stage1": {key: {"checked": True, "label": ..., "explanation": ...,
                       "categoryTitle": ...}, ...},
      "stage2": {...},
      "finalUpliftPercent": "75"
    }

Labels are mapped back to QUESTION_BLOCKS keys via the lookup in
``templates.label_to_key_lookup``. Unknown labels are reported on stderr.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pdfplumber

from templates import label_to_key_lookup

# Section markers as they appear in the PDF — UPPERCASE per addSectionHeader.
SECTION_PATTERNS: dict[str, re.Pattern[str]] = {
    "case_details": re.compile(r"^CASE DETAILS\s*$", re.MULTILINE),
    "panel_membership": re.compile(r"^PANEL MEMBERSHIP\s*$", re.MULTILINE),
    "stage1": re.compile(r"^STAGE 1: THRESHOLD TEST SELECTIONS\s*$", re.MULTILINE),
    "stage2": re.compile(r"^STAGE 2: LEVEL OF ENHANCEMENT FACTORS\s*$", re.MULTILINE),
    "proposed_uplift": re.compile(r"^PROPOSED UPLIFT\s*$", re.MULTILINE),
    "disclaimer": re.compile(r"^DISCLAIMER\s*$", re.MULTILINE),
}

# Per-page footer stamped by addFooter — strip before parsing.
FOOTER_PATTERN = re.compile(
    r"CONFIDENTIAL\s+[—-]\s+FOR LAA SUBMISSION\s+Page\s+\d+\s+of\s+\d+\s+Woodruff Billing Ltd"
)

# Per-page header rendered by addHeader.
HEADER_PATTERN = re.compile(
    r"W\s*Woodruff Billing Ltd\.\s+LAA Uplift Enhancement\s*\|\s*Data Summary"
)


def read_pdf_text(pdf_path: Path) -> str:
    """Read all pages and concatenate their text."""
    parts: list[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(parts)


def normalise_text(text: str) -> str:
    """Strip per-page headers and footers; collapse excessive blank lines."""
    text = FOOTER_PATTERN.sub("", text)
    text = HEADER_PATTERN.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def section_slice(text: str, name: str) -> str:
    """Return the text of *name* section, ending at the next known section."""
    pat = SECTION_PATTERNS[name]
    m = pat.search(text)
    if not m:
        return ""
    start = m.end()
    next_starts = []
    for other_name, other_pat in SECTION_PATTERNS.items():
        if other_name == name:
            continue
        m2 = other_pat.search(text, start)
        if m2:
            next_starts.append(m2.start())
    end = min(next_starts) if next_starts else len(text)
    return text[start:end].strip()


def extract_case_details(text: str) -> dict:
    block = section_slice(text, "case_details")
    fields: dict[str, str] = {}
    pairs = [
        (r"Fee Earner:\s+(.+)", "feeEarnerName"),
        (r"Matter Type:\s+(.+)", "matterType"),
        (r"Case / Matter Name:\s+(.+)", "caseMatterName"),
    ]
    for pattern, key in pairs:
        m = re.search(pattern, block)
        fields[key] = m.group(1).strip() if m else ""
    return fields


def extract_panel(text: str, label_keys: dict[str, str]) -> dict:
    block = section_slice(text, "panel_membership")
    if not block or "None selected." in block:
        return {}
    result: dict[str, dict] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped.startswith("•"):
            continue
        label = stripped.lstrip("•").strip()
        key = label_keys.get(label)
        if not key:
            print(f"narrate: unknown panel label {label!r}", file=sys.stderr)
            continue
        result[key] = {"checked": True, "label": label}
    return result


def extract_criteria(
    text: str, section_name: str, label_keys: dict[str, str]
) -> dict:
    """Parse Stage 1 or Stage 2 criteria. Each ticked item in the PDF is::

        •  <label>
        <categoryTitle>
        Explanation: <text, possibly wrapped over multiple lines>
    """
    block = section_slice(text, section_name)
    if not block:
        return {}
    first_line = block.split("\n", 1)[0]
    if "No Stage" in first_line and "selected" in first_line:
        return {}

    # Split into chunks each beginning with a bullet at start-of-line.
    chunks = re.split(r"\n(?=•\s)", "\n" + block)
    result: dict[str, dict] = {}
    for chunk in chunks:
        chunk = chunk.strip()
        if not chunk.startswith("•"):
            continue
        lines = [ln.rstrip() for ln in chunk.splitlines()]
        label = lines[0].lstrip("•").strip()

        category_parts: list[str] = []
        explanation_parts: list[str] = []
        in_explanation = False
        for line in lines[1:]:
            stripped = line.strip()
            if not in_explanation and stripped.startswith("Explanation:"):
                in_explanation = True
                explanation_parts.append(stripped[len("Explanation:") :].strip())
            elif in_explanation:
                if stripped:
                    explanation_parts.append(stripped)
            else:
                if stripped:
                    category_parts.append(stripped)

        category_title = " ".join(category_parts).strip()
        explanation = " ".join(explanation_parts).strip()
        key = label_keys.get(label)
        if not key:
            print(
                f"narrate: unknown criterion label in {section_name}: {label!r}",
                file=sys.stderr,
            )
            continue
        result[key] = {
            "checked": True,
            "label": label,
            "categoryTitle": category_title,
            "explanation": explanation,
        }
    return result


def extract_uplift_percent(text: str) -> str:
    block = section_slice(text, "proposed_uplift")
    m = re.search(r"Proposed Uplift Percentage:\s*([\d.]+)\s*%", block)
    return m.group(1) if m else ""


def extract_formdata(pdf_path: str | Path) -> dict:
    """Read a Collator-generated PDF and return its formData equivalent."""
    pdf_path = Path(pdf_path)
    raw = read_pdf_text(pdf_path)
    text = normalise_text(raw)
    label_keys = label_to_key_lookup()
    return {
        "caseDetails": extract_case_details(text),
        "panelMembership": extract_panel(text, label_keys),
        "stage1": extract_criteria(text, "stage1", label_keys),
        "stage2": extract_criteria(text, "stage2", label_keys),
        "finalUpliftPercent": extract_uplift_percent(text),
    }


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <pdf_path>", file=sys.stderr)
        sys.exit(1)
    data = extract_formdata(sys.argv[1])
    print(json.dumps(data, indent=2, ensure_ascii=False))
