"""Extract solicitor answers from a PDF generated by the Uplift Collator web app.

The PDF structure is produced by ``generatePdfSummary`` in ``script.js`` via
helpers ``addSectionHeader`` (renders UPPERCASE titles), ``addDetail`` (renders
``Label:  Value``) and ``addCriterion`` (renders three lines per ticked item:
bullet+label, category, ``Explanation: ...``). We parse against that structure.

Output shape mirrors the in-app ``formData``::

    {
      "caseDetails": {"feeEarnerName": ..., "matterType": ..., "caseMatterName": ...},
      "panelMembership": {key: {"checked": True, "label": ...}, ...},
      "stage1": {key: {"checked": True, "label": ..., "explanation": ...,
                       "categoryTitle": ...}, ...},
      "stage2": {...},
      "finalUpliftPercent": "75"
    }

Labels are mapped back to QUESTION_BLOCKS keys via the lookup in
``templates.label_to_key_lookup``. Unknown labels are reported on stderr.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pdfplumber

from templates import label_to_key_lookup

# Section markers as they appear in the PDF — UPPERCASE per addSectionHeader.
SECTION_PATTERNS: dict[str, re.Pattern[str]] = {
    "case_details": re.compile(r"^CASE DETAILS\s*$", re.MULTILINE),
    "panel_membership": re.compile(r"^PANEL MEMBERSHIP\s*$", re.MULTILINE),
    "stage1": re.compile(r"^STAGE 1: THRESHOLD TEST SELECTIONS\s*$", re.MULTILINE),
    "stage2": re.compile(r"^STAGE 2: LEVEL OF ENHANCEMENT FACTORS\s*$", re.MULTILINE),
    "proposed_uplift": re.compile(r"^PROPOSED UPLIFT\s*$", re.MULTILINE),
    "disclaimer": re.compile(r"^DISCLAIMER\s*$", re.MULTILINE),
}

# Per-page footer stamped by addFooter — strip before parsing.
FOOTER_PATTERN = re.compile(
    r"CONFIDENTIAL\s+[—-]\s+FOR LAA SUBMISSION\s+Page\s+\d+\s+of\s+\d+\s+Woodruff Billing Ltd"
)

# Per-page header rendered by addHeader.
HEADER_PATTERN = re.compile(
    r"W\s*Woodruff Billing Ltd\.\s+LAA Uplift Enhancement\s*\|\s*Data Summary"
)


def read_pdf_text(pdf_path: Path) -> str:
    """Read all pages and concatenate their text."""
    parts: list[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(parts)


def normalise_text(text: str) -> str:
    """Strip per-page headers and footers; collapse excessive blank lines."""
    text = FOOTER_PATTERN.sub("", text)
    text = HEADER_PATTERN.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def section_slice(text: str, name: str) -> str:
    """Return the text of *name* section, ending at the next known section."""
    pat = SECTION_PATTERNS[name]
    m = pat.search(text)
    if not m:
        return ""
    start = m.end()
    next_starts = []
    for other_name, other_pat in SECTION_PATTERNS.items():
        if other_name == name:
            continue
        m2 = other_pat.search(text, start)
        if m2:
            next_starts.append(m2.start())
    end = min(next_starts) if next_starts else len(text)
    return text[start:end].strip()


def extract_case_details(text: str) -> dict:
    block = section_slice(text, "case_details")
    fields: dict[str, str] = {}
    pairs = [
        (r"Fee Earner:\s+(.+)", "feeEarnerName"),
        (r"Matter Type:\s+(.+)", "matterType"),
        (r"Case / Matter Name:\s+(.+)", "caseMatterName"),
    ]
    for pattern, key in pairs:
        m = re.search(pattern, block)
        fields[key] = m.group(1).strip() if m else ""
    return fields


def extract_panel(text: str, label_keys: dict[str, str]) -> dict:
    block = section_slice(text, "panel_membership")
    if not block or "None selected." in block:
        return {}
    result: dict[str, dict] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped.startswith("•"):
            continue
        label = stripped.lstrip("•").strip()
        key = label_keys.get(label)
        if not key:
            print(f"narrate: unknown panel label {label!r}", file=sys.stderr)
            continue
        result[key] = {"checked": True, "label": label}
    return result


def extract_criteria(
    text: str, section_name: str, label_keys: dict[str, str]
) -> dict:
    """Parse Stage 1 or Stage 2 criteria. Each ticked item in the PDF is::

        •  <label>
        <categoryTitle>
        Explanation: <text, possibly wrapped over multiple lines>
    """
    block = section_slice(text, section_name)
    if not block:
        return {}
    first_line = block.split("\n", 1)[0]
    if "No Stage" in first_line and "selected" in first_line:
        return {}

    # Split into chunks each beginning with a bullet at start-of-line.
    chunks = re.split(r"\n(?=•\s)", "\n" + block)
    result: dict[str, dict] = {}
    for chunk in chunks:
        chunk = chunk.strip()
        if not chunk.startswith("•"):
            continue
        lines = [ln.rstrip() for ln in chunk.splitlines()]
        label = lines[0].lstrip("•").strip()

        category_parts: list[str] = []
        explanation_parts: list[str] = []
        in_explanation = False
        for line in lines[1:]:
            stripped = line.strip()
            if not in_explanation and stripped.startswith("Explanation:"):
                in_explanation = True
                explanation_parts.append(stripped[len("Explanation:") :].strip())
            elif in_explanation:
                if stripped:
                    explanation_parts.append(stripped)
            else:
                if stripped:
                    category_parts.append(stripped)

        category_title = " ".join(category_parts).strip()
        explanation = " ".join(explanation_parts).strip()
        key = label_keys.get(label)
        if not key:
            print(
                f"narrate: unknown criterion label in {section_name}: {label!r}",
                file=sys.stderr,
            )
            continue
        result[key] = {
            "checked": True,
            "label": label,
            "categoryTitle": category_title,
            "explanation": explanation,
        }
    return result


def extract_uplift_percent(text: str) -> str:
    block = section_slice(text, "proposed_uplift")
    m = re.search(r"Proposed Uplift Percentage:\s*([\d.]+)\s*%", block)
    return m.group(1) if m else ""


class NoDataExtracted(Exception):
    """The PDF yielded nothing worth narrating.

    Raised so the run stops at the PDF rather than building an empty skeleton,
    spending a model call on it, and reporting the resulting nonsense as a
    citation failure. The message is written for the person holding the PDF,
    and contains no client text.
    """


def extraction_is_empty(formdata: dict) -> bool:
    """True when no Stage 1 or Stage 2 criterion was recovered.

    Panel membership and the uplift percentage are not enough on their own —
    the criteria *are* the narrative. A submission with neither has nothing to
    justify, so there is nothing to write.
    """
    return not (formdata.get("stage1") or formdata.get("stage2"))


def explain_empty_extraction(pdf_path: str | Path) -> str:
    """Plain-English reason an extraction came back empty.

    Built from :func:`diagnose`, so it reports structure only — never a field
    value, an explanation, or any other client text. Safe to print to a
    terminal, paste into a message, or write into a log.
    """
    d = diagnose(pdf_path)
    matched = {n for n, s in d["sections"].items() if s["matched"]}
    ticks = sum(
        s.get("bullet_lines", 0)
        for n, s in d["sections"].items()
        if n in ("stage1", "stage2")
    )

    if d["raw_chars"] == 0:
        made_by = d.get("producer") or d.get("creator") or ""
        flattened = d.get("largest_image_page_coverage", 0) >= 0.5

        head = (
            "This PDF has no text layer — every page is a picture of the page\n"
            "rather than text. Nothing can be read out of it.\n"
            "(That is also why you cannot select any text in it yourself.)\n"
        )
        if made_by:
            head += f"\nThe file says it was last written by: {made_by}\n"

        if flattened:
            head += (
                "\nThe page content is one large image, so this is a *flattened*\n"
                "copy of a real document rather than a scan of paper.\n"
            )

        return head + (
            "\nThe Collator's own PDF always has selectable text, so the\n"
            "flattening happened after the app produced the file. The usual\n"
            "culprits, in order of likelihood:\n"
            "  - Acrobat's 'Print as image' option, which is a sticky checkbox\n"
            "    under Advanced print settings and rasterises everything.\n"
            "  - A case-management or document-management system that flattens\n"
            "    PDFs when a file is filed into it or exported from it.\n"
            "  - Secure-email attachment sanitising, which rebuilds an incoming\n"
            "    PDF as images to strip anything active from it.\n"
            "  - The document being printed on paper and scanned back in.\n\n"
            "Fix: ask for the file the app actually saved —\n"
            "LAA_Uplift_Data_Summary.pdf, straight from the browser's Downloads\n"
            "folder, before it went anywhere else. Do not re-key or OCR it: on\n"
            "an audited claim a mis-read page count or percentage is worse than\n"
            "no narrative at all."
        )

    if not d.get("made_by_the_app", True) and (d.get("producer") or d.get("creator")):
        producer = d.get("producer") or d.get("creator")
        return (
            "This PDF has text, but none of the Collator's section headings —\n"
            "CASE DETAILS, PANEL MEMBERSHIP, STAGE 1, STAGE 2, PROPOSED UPLIFT.\n\n"
            f"It also says it was written by: {producer}\n"
            "The Collator writes its PDFs with jsPDF, so this file was made or\n"
            "rebuilt by something else.\n\n"
            "Fix: ask for the file the app itself saved —\n"
            "LAA_Uplift_Data_Summary.pdf, straight from the Downloads folder."
        )

    if not matched:
        return (
            "This does not look like an Uplift Collator PDF.\n"
            f"It has text ({d['raw_chars']} characters over {d['pages']} page(s)) but\n"
            "none of the section headings the Collator writes — CASE DETAILS,\n"
            "PANEL MEMBERSHIP, STAGE 1, STAGE 2, PROPOSED UPLIFT.\n\n"
            "The two usual causes:\n"
            "  - The browser's own Print-to-PDF was used instead of the app's\n"
            '    "Generate PDF Summary" button. Printing captures the on-screen\n'
            "    page, which has none of this structure.\n"
            "  - The PDF came from a different document altogether.\n\n"
            "Fix: re-generate it from the app's own button."
        )

    if {"stage1", "stage2"} & matched and ticks == 0:
        return (
            "This is an Uplift Collator PDF, but no criteria were ticked in it.\n"
            "Stage 1 and Stage 2 are both empty, so there is nothing to justify\n"
            "and no narrative to write.\n\n"
            "Fix: the solicitor needs to complete the questionnaire — tick the\n"
            "criteria that apply and give each one an explanation — then\n"
            "re-generate the PDF."
        )

    if not {"stage1", "stage2"} & matched:
        return (
            "This PDF has Collator sections but no Stage 1 or Stage 2 section.\n"
            f"Found: {', '.join(sorted(matched))}.\n\n"
            "That usually means it was generated by an older version of the web\n"
            "app whose headings differ.\n\n"
            "Fix: re-generate the PDF from the current app."
        )

    return (
        f"The Stage sections were found and contain {ticks} ticked item(s), but\n"
        "none of their labels matched the current questionnaire, so nothing\n"
        "could be recovered. Look for 'unknown criterion label' lines above.\n\n"
        "That means the PDF was generated against an older version of\n"
        "content-data.js whose wording has since changed.\n\n"
        "Fix: re-generate the PDF from the current app."
    )


def extract_formdata(pdf_path: str | Path) -> dict:
    """Read a Collator-generated PDF and return its formData equivalent."""
    pdf_path = Path(pdf_path)
    raw = read_pdf_text(pdf_path)
    text = normalise_text(raw)
    label_keys = label_to_key_lookup()
    return {
        "caseDetails": extract_case_details(text),
        "panelMembership": extract_panel(text, label_keys),
        "stage1": extract_criteria(text, "stage1", label_keys),
        "stage2": extract_criteria(text, "stage2", label_keys),
        "finalUpliftPercent": extract_uplift_percent(text),
    }


# PDF producers that mean "this file was rebuilt by something after the app
# made it". jsPDF is the only one the Collator itself ever writes.
JSPDF_PRODUCER = re.compile(r"jsPDF", re.IGNORECASE)


def diagnose(pdf_path: str | Path) -> dict:
    """Structural diagnostics for an extraction failure.

    Returns *only* shape/structure information — no raw text, no
    explanations, no field values — so the output is safe to share
    even when the input PDF contains GDPR-sensitive client data.

    ``producer``/``creator`` are the PDF's own software-name metadata, which
    names whatever last wrote the file. Deliberately *only* those two: Title,
    Author, Subject and Keywords can carry a client name, so they are never
    read. That pair is what distinguishes "the app made this" from "something
    rebuilt it afterwards", which is the difference between a bug in the
    extractor and a file that arrived already flattened.
    """
    pdf_path = Path(pdf_path)
    with pdfplumber.open(pdf_path) as pdf:
        n_pages = len(pdf.pages)
        per_page_chars = [len(p.extract_text() or "") for p in pdf.pages]
        meta = pdf.metadata or {}
        producer = str(meta.get("Producer", "") or "")
        creator = str(meta.get("Creator", "") or "")
        # Is the page a picture of itself? A flattened PDF has no characters
        # and one large image; a normal one has characters and no image.
        n_images = 0
        image_coverage = 0.0
        n_vectors = 0
        for page in pdf.pages:
            n_images += len(page.images)
            n_vectors += len(page.curves) + len(page.rects)
            page_area = float(page.width) * float(page.height)
            for img in page.images:
                if page_area <= 0:
                    continue
                area = (abs(float(img["x1"]) - float(img["x0"]))
                        * abs(float(img["bottom"]) - float(img["top"])))
                image_coverage = max(image_coverage, area / page_area)
    raw = read_pdf_text(pdf_path)
    text = normalise_text(raw)

    # Per-section presence and shape
    sections: dict[str, dict] = {}
    for name in SECTION_PATTERNS:
        m = SECTION_PATTERNS[name].search(text)
        if not m:
            sections[name] = {"matched": False}
            continue
        block = section_slice(text, name)
        lines = block.splitlines()
        bullet_lines = sum(1 for ln in lines if ln.lstrip().startswith("•"))
        explanation_markers = sum(
            1 for ln in lines if ln.lstrip().startswith("Explanation:")
        )
        sections[name] = {
            "matched": True,
            "start_offset": m.start(),
            "block_chars": len(block),
            "block_lines": len(lines),
            "bullet_lines": bullet_lines,
            "explanation_markers": explanation_markers,
        }

    return {
        "pdf": pdf_path.name,
        "pages": n_pages,
        "per_page_chars": per_page_chars,
        "raw_chars": len(raw),
        "normalised_chars": len(text),
        "header_matches": len(HEADER_PATTERN.findall(raw)),
        "footer_matches": len(FOOTER_PATTERN.findall(raw)),
        "producer": producer,
        "creator": creator,
        "made_by_the_app": bool(JSPDF_PRODUCER.search(producer)),
        "images": n_images,
        "largest_image_page_coverage": round(image_coverage, 3),
        "vector_objects": n_vectors,
        "sections": sections,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 3 or (
        len(sys.argv) == 3 and sys.argv[1] != "--debug"
    ):
        print(f"Usage: {sys.argv[0]} [--debug] <pdf_path>", file=sys.stderr)
        sys.exit(1)
    if len(sys.argv) == 3:
        out = diagnose(sys.argv[2])
    else:
        out = extract_formdata(sys.argv[1])
    print(json.dumps(out, indent=2, ensure_ascii=False))
