"""Extract solicitor answers from a .docx generated by the Uplift Collator.

The document is produced by ``buildUpliftDocx`` in ``docx-summary.js`` (repo
root). Its contract is **paragraph equality**: every heading, detail line,
bullet and sentinel is exactly one Word paragraph, and python-docx returns each
paragraph whole. That is deliberately a stronger contract than the PDF's text
layer, and it retires the two defect classes that forced five review rounds of
hardening into ``extract.py``:

* **Nothing wraps.** A PDF label wider than its column silently became two
  lines that matched nothing; ``_resolve_wrapped_label`` exists only for that.
  A docx paragraph comes back whole however long it is, so this module has no
  rejoining logic at all — and must never grow any, because joining is where
  the PDF path's ambiguity came from.
* **Nothing pasted can imitate structure.** Text a solicitor pastes into an
  explanation textarea lives *inside* the explanation's own paragraph — the
  generator encodes its newlines as ``<w:br/>``, never as new paragraphs — so
  no line of it can ever *equal* a heading paragraph. The PDF path's
  last-occurrence and status-line hardening exists because pasted lines were
  indistinguishable from real headings there. Here they cannot occur in an
  unedited file; the evidence section keeps the last-occurrence rule anyway,
  because a document edited in Word afterwards can contain anything.

Everything semantic is shared with the PDF path rather than re-implemented:
label lookup (``templates.label_to_key_lookup``), the section-prefix guard
(``extract._SECTION_KEY_PREFIXES``), the unrecognised-label records
(``extract._unrecognised``), and the meaning of every downstream field. A
ticked line whose label matches nothing is recorded under ``unrecognised``
so the caller stops the run — never dropped.

The output shape is identical to ``extract.extract_formdata``'s.
"""

from __future__ import annotations

import re
import zipfile
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.opc.exceptions import PackageNotFoundError

from templates import label_to_key_lookup

# ── The paragraph contract ─────────────────────────────────────────────────
#
# Section headings exactly as buildUpliftDocx writes them. A heading matches
# only when a paragraph's whole text (whitespace-trimmed) equals one of these.
SECTION_HEADINGS: dict[str, str] = {
    "case_details": "CASE DETAILS",
    "panel_membership": "PANEL MEMBERSHIP",
    "stage1": "STAGE 1: THRESHOLD TEST SELECTIONS",
    "stage2": "STAGE 2: LEVEL OF ENHANCEMENT FACTORS",
    "proposed_uplift": "PROPOSED UPLIFT",
    "evidence_on_file": "EVIDENCE ON FILE",
    "disclaimer": "DISCLAIMER",
}

# The canonical order the generator writes sections in. Stage 2 is absent
# only where the threshold was neither met nor deemed (which the form's
# download gate should prevent, but absence is not damage); every heading
# that IS present must appear in this order, exactly once.
_CANONICAL_ORDER = [
    "case_details", "panel_membership", "stage1", "stage2",
    "proposed_uplift", "evidence_on_file", "disclaimer",
]

# The two case-detail separators. addDetail prints "Label:  Value" with two
# spaces; matching tolerates one-or-more so a Word autocorrect that collapses
# runs of spaces cannot silently blank all four fields.
_DETAIL_FIELDS: list[tuple[str, str]] = [
    ("feeEarnerName", "Fee Earner:"),
    ("matterType", "Matter Type:"),
    ("caseMatterName", "Case / Matter Name:"),
    ("courtLevel", "Court:"),
]

# The deemed-threshold sentence, compared whitespace-collapsed but otherwise
# exact — it is an extraction contract, printed by the generator only inside
# Stage 1 and read back only from there.
_THRESHOLD_DEEMED_TEXT = (
    "Threshold test: deemed satisfied by panel membership (Spec Para 7.23(a))."
)

# The evidence pair — same two independent statements as the PDF contract,
# and they must agree before the confirmation counts (see
# extract.extract_evidence_confirmation for why one is not enough). The
# sentence is matched WHOLE, whitespace-collapsed: a prefix match would have
# accepted "…is held on the case file" with anything appended after it —
# including a negation — and an agreeing pair whose second statement can be
# made to disagree invisibly is no pair at all. (The PDF path matches a
# prefix because wrapping could break the sentence anywhere; nothing wraps
# here, so the docx contract affords the stronger test.)
_EVIDENCE_STATUS_RE = re.compile(r"^Evidence on file:\s*(Not confirmed|Confirmed)\s*$")
_EVIDENCE_CONFIRMED_SENTENCE = (
    "The fee earner confirms that evidence supporting the matters set out "
    "above is held on the case file."
)

_UPLIFT_RE = re.compile(r"Proposed Uplift Percentage:\s*([\d.]+)\s*%")


def read_docx_paragraphs(path: str | Path) -> list[str]:
    """Every body paragraph's text, in document order.

    Header and footer parts are real Word headers/footers and are not body
    paragraphs, so the page furniture never appears here — there is no docx
    equivalent of the PDF path's header/footer stripping. python-docx renders
    ``<w:br/>`` as ``\\n`` *inside* a paragraph's text, which is exactly the
    property the paste-immunity argument rests on.
    """
    doc = Document(str(path))
    return [p.text for p in doc.paragraphs]


def _collapse(text: str) -> str:
    return " ".join(text.split())


def _section_indexes(paragraphs: list[str]) -> dict[str, int]:
    """Index of each section's heading paragraph (first occurrence).

    Occurrence-picking is safe here only because :func:`structural_damage`
    refuses any document in which a heading occurs twice — callers that
    extract must check it first. In an unedited Collator docx a duplicate is
    impossible; in an edited one, choosing between occurrences is exactly how
    a pasted fake section could outrank a real one, so the answer to a
    duplicate is a stop, not a preference.
    """
    found: dict[str, int] = {}
    for i, para in enumerate(paragraphs):
        text = para.strip()
        for name, heading in SECTION_HEADINGS.items():
            if text == heading and name not in found:
                found[name] = i
    return found


def structural_damage(paragraphs: list[str]) -> list[str]:
    """Why this document's section structure cannot be trusted, or [].

    The generator writes each heading exactly once, in a fixed order. A
    heading appearing twice, or headings out of that order, can only mean the
    document was edited after download — and an edited structure is one in
    which choosing an occurrence could file a pasted fake section as the real
    one (a fake ``PROPOSED UPLIFT`` above the genuine section would otherwise
    supply the percentage). Damage stops the run; it never picks.
    """
    counts: dict[str, int] = {name: 0 for name in SECTION_HEADINGS}
    for para in paragraphs:
        text = para.strip()
        for name, heading in SECTION_HEADINGS.items():
            if text == heading:
                counts[name] += 1
    problems = [
        f"the {SECTION_HEADINGS[name]!r} heading appears {n} times"
        for name, n in counts.items() if n > 1
    ]
    indexes = _section_indexes(paragraphs)
    present = [name for name in _CANONICAL_ORDER if name in indexes]
    positions = [indexes[name] for name in present]
    if positions != sorted(positions):
        problems.append(
            "the section headings are not in the order the app writes them"
        )
    return problems


def section_paragraphs(paragraphs: list[str], name: str) -> list[str]:
    """The paragraphs of *name* section, ending at the next section heading."""
    indexes = _section_indexes(paragraphs)
    if name not in indexes:
        return []
    start = indexes[name] + 1
    end = len(paragraphs)
    for other, idx in indexes.items():
        if other != name and start <= idx < end:
            end = idx
    return paragraphs[start:end]


def extract_case_details(paragraphs: list[str]) -> dict:
    """The four case-detail fields — one paragraph each, no wrap, no ambiguity.

    This is the reader the PDF path could never have: because a detail line is
    a single paragraph, a matter name reading "In the High Court: Re X and Y"
    can never masquerade as the Court field. The first paragraph carrying each
    field's label wins; the value is everything after the colon.

    Internal whitespace is preserved — the PDF path collapsed it because
    wrapping forced a rejoin; nothing forces one here, and a value must come
    back as it was written. Only newlines (impossible from the form's inputs,
    so damage if present) are folded to spaces, and the delimiter's own
    spaces are trimmed.
    """
    block = section_paragraphs(paragraphs, "case_details")
    fields: dict[str, str] = {}
    for para in block:
        text = para.strip()
        for key, prefix in _DETAIL_FIELDS:
            if key not in fields and text.startswith(prefix):
                fields[key] = text[len(prefix):].replace("\n", " ").strip()
    for key, _prefix in _DETAIL_FIELDS:
        fields.setdefault(key, "")
    return fields


def _iter_bullet_items(block: list[str]):
    """Yield (label, category_paragraphs, explanation) per bullet item.

    An item is one bullet paragraph plus everything until the next bullet.
    Explanations are exactly one paragraph in the generator's output; if an
    edited document has split one, later non-bullet paragraphs join it with a
    newline rather than being dropped — the same never-lose-text rule as the
    PDF path, without its guessing.
    """
    label = None
    category: list[str] = []
    explanation_parts: list[str] = []
    in_explanation = False
    for para in block:
        text = para.strip()
        if not text:
            continue
        if text.startswith("•"):
            if label is not None:
                yield label, category, "\n".join(explanation_parts).strip()
            label = text.lstrip("•").strip()
            category, explanation_parts, in_explanation = [], [], False
            continue
        if label is None:
            # Text before the first bullet: the empty-section sentinel or the
            # deemed line, handled by the callers — never part of an item.
            continue
        if not in_explanation and text.startswith("Explanation:"):
            in_explanation = True
            explanation_parts.append(text[len("Explanation:"):].strip())
        elif in_explanation:
            explanation_parts.append(text)
        else:
            category.append(text)
    if label is not None:
        yield label, category, "\n".join(explanation_parts).strip()


def extract_panel(
    paragraphs: list[str],
    label_keys: dict[str, str],
    unmatched: list[dict] | None = None,
) -> dict:
    # Imported here, not at module top: extract.py imports this module inside
    # its dispatcher, so a top-level import back would be circular.
    from extract import _SECTION_KEY_PREFIXES, _unrecognised

    block = section_paragraphs(paragraphs, "panel_membership")
    if not block or any("None selected." == p.strip() for p in block):
        return {}
    result: dict[str, dict] = {}
    known = list(label_keys)
    for label, _category, _explanation in _iter_bullet_items(block):
        key = label_keys.get(label)
        # Same guard as the PDF path, for the same reason: panel membership
        # carries a guaranteed 15% (CAG 12.20), so a criterion label read
        # under this heading is a damaged document, not a lesser problem.
        if key and not key.startswith(_SECTION_KEY_PREFIXES["panelMembership"]):
            key = None
        if not key:
            if unmatched is not None:
                unmatched.append(_unrecognised("panelMembership", label, known))
            continue
        result[key] = {"checked": True, "label": label}
    return result


def extract_criteria(
    paragraphs: list[str],
    section_name: str,
    label_keys: dict[str, str],
    unmatched: list[dict] | None = None,
) -> dict:
    from extract import _SECTION_KEY_PREFIXES, _unrecognised

    block = section_paragraphs(paragraphs, section_name)
    if not block:
        return {}
    first = block[0].strip()
    if "No Stage" in first and "selected" in first:
        return {}

    result: dict[str, dict] = {}
    known = list(label_keys)
    for label, category, explanation in _iter_bullet_items(block):
        key = label_keys.get(label)
        # A key from the wrong stage is treated as no key at all — exact
        # matching cannot stop a damaged label from *being* a different real
        # label, so the key must belong to the section it was read from.
        # (Full worked example: extract.extract_criteria.)
        if key and not key.startswith(_SECTION_KEY_PREFIXES[section_name]):
            key = None
        if not key:
            if unmatched is not None:
                unmatched.append(
                    _unrecognised(
                        section_name,
                        label,
                        known,
                        categoryTitle=" ".join(category).strip(),
                        explanation=explanation,
                    )
                )
            continue
        result[key] = {
            "checked": True,
            "label": label,
            "categoryTitle": " ".join(category).strip(),
            "explanation": explanation,
        }
    return result


def extract_threshold_deemed(paragraphs: list[str]) -> bool:
    """Whether the document affirmatively states the deemed threshold.

    A positive reading of a paragraph that is present inside Stage 1 — never
    an inference from an absent section, and never accepted from anywhere
    else in the document. Same reasoning as the PDF path
    (extract.extract_threshold_deemed); the docx difference is only that the
    sentence is one whole paragraph, so no wrapping tolerance is needed.
    """
    block = section_paragraphs(paragraphs, "stage1")
    return any(_collapse(p) == _THRESHOLD_DEEMED_TEXT for p in block)


def extract_uplift_percent(paragraphs: list[str]) -> str:
    for para in section_paragraphs(paragraphs, "proposed_uplift"):
        m = _UPLIFT_RE.search(para)
        if m:
            return m.group(1)
    return ""


def extract_evidence_confirmation(paragraphs: list[str]) -> bool:
    """Whether the fee earner confirmed the file holds the evidence.

    Strict, defaulting to False in every doubtful case — the sentence this
    gates is an assertion to the LAA about a file nobody here has seen. Both
    the status paragraph and the sentence paragraph must agree, in the
    section's own two leading paragraphs, in that order. A document edited
    into any other shape reads as not confirmed, the same answer every other
    kind of damage gets.
    """
    block = section_paragraphs(paragraphs, "evidence_on_file")
    if len(block) < 2:
        return False
    status = _EVIDENCE_STATUS_RE.match(block[0].strip())
    if not status or status.group(1) != "Confirmed":
        return False
    return _collapse(block[1]) == _EVIDENCE_CONFIRMED_SENTENCE


def _empty_formdata() -> dict:
    return {
        "caseDetails": {key: "" for key, _p in _DETAIL_FIELDS},
        "panelMembership": {},
        "stage1": {},
        "stage2": {},
        "finalUpliftPercent": "",
        "evidenceOnFileConfirmed": False,
        "thresholdDeemed": False,
    }


def extract_formdata_docx(path: str | Path) -> dict:
    """Read a Collator-generated .docx and return its formData equivalent.

    A document whose section structure is damaged — a heading duplicated or
    reordered, which only an edit after download can produce — yields an
    all-empty result rather than a best guess: the caller's empty-extraction
    stop then fires and :func:`explain_empty_extraction_docx` names the
    duplication. Extracting *around* damaged structure is how a pasted fake
    section could outrank a real one, so nothing is read at all.
    """
    paragraphs = read_docx_paragraphs(path)
    if structural_damage(paragraphs):
        return _empty_formdata()
    label_keys = label_to_key_lookup()
    unmatched: list[dict] = []
    data = {
        "caseDetails": extract_case_details(paragraphs),
        "panelMembership": extract_panel(paragraphs, label_keys, unmatched),
        "stage1": extract_criteria(paragraphs, "stage1", label_keys, unmatched),
        "stage2": extract_criteria(paragraphs, "stage2", label_keys, unmatched),
        "finalUpliftPercent": extract_uplift_percent(paragraphs),
        "evidenceOnFileConfirmed": extract_evidence_confirmation(paragraphs),
        "thresholdDeemed": extract_threshold_deemed(paragraphs),
    }
    if unmatched:
        data["unrecognised"] = unmatched
    return data


# ── Diagnostics ────────────────────────────────────────────────────────────
#
# The docx equivalent of extract.diagnose: structure only, never a field
# value, an explanation, a filename, or a person's name — so the output is
# safe to share even when the document holds GDPR-sensitive client data.
#
# The redactions are deliberate and each replaces something the PDF
# diagnostics never had to face. `dc:creator` is the app's own stamp
# ("Uplift Collator v1.13") in an unedited file, but in a foreign or
# Word-authored document it is a PERSON — the same reason diagnose_pdf
# deliberately never reads Title/Author/Subject/Keywords. So the creator
# string is echoed only when it is recognisably the app's own; otherwise the
# reader gets `made_by_the_app: false` and no name. `lastModifiedBy` is
# almost always a person (Word writes the Office account name on save), so
# only the boolean fact that somebody re-saved the file survives. The
# filename is omitted for the same reason — it carries the matter name, and
# the person running --debug can see what file they ran it on.

# Exactly what the Collator writes into dc:creator — "Uplift Collator v1.13"
# and nothing else. A full match, not a substring: a creator reading
# "Uplift Collator v1.13 — Priya Solicitor" is NOT the app's pristine stamp,
# and treating it as one would echo the person's name through the "safe"
# branch. (Round-2 review finding, 7 August 2026.)
_APP_CREATOR_RE = re.compile(r"^Uplift Collator v[\d.]+$")


def _iso(moment: datetime | None) -> str:
    return moment.isoformat() if moment else ""


def diagnose_docx(path: str | Path) -> dict:
    """Structural diagnostics for a .docx extraction failure."""
    path = Path(path)

    if not zipfile.is_zipfile(path):
        return {"readable": False, "failure": "not_a_zip"}
    try:
        doc = Document(str(path))
    except (PackageNotFoundError, KeyError, ValueError) as exc:
        # A zip that is not a Word package — wrong file, or a docx whose
        # parts were stripped by whatever rewrote it.
        return {
            "readable": False,
            "failure": f"not_a_word_package: {type(exc).__name__}",
        }

    paragraphs = [p.text for p in doc.paragraphs]
    cp = doc.core_properties
    creator = cp.author or ""
    last_modified_by = cp.last_modified_by or ""
    created, modified = cp.created, cp.modified
    made_by_the_app = bool(_APP_CREATOR_RE.match(creator.strip()))

    indexes = _section_indexes(paragraphs)
    sections: dict[str, dict] = {}
    for name in SECTION_HEADINGS:
        if name not in indexes:
            sections[name] = {"matched": False}
            continue
        block = section_paragraphs(paragraphs, name)
        sections[name] = {
            "matched": True,
            "paragraph_index": indexes[name],
            "block_paragraphs": len(block),
            "bullet_lines": sum(1 for p in block if p.strip().startswith("•")),
            "explanation_markers": sum(
                1 for p in block if p.strip().startswith("Explanation:")
            ),
        }

    return {
        "readable": True,
        "paragraphs": len(paragraphs),
        # The Collator writes no tables, and extraction walks doc.paragraphs,
        # which never enters a table cell — so content edited into a table
        # would vanish silently. A non-zero count here is the one signal of
        # that shape a triager gets.
        "tables": len(doc.tables),
        "raw_chars": sum(len(p) for p in paragraphs),
        "creator": creator if made_by_the_app else "",
        "made_by_the_app": made_by_the_app,
        # True when somebody (or something) re-saved the file after the app
        # wrote it. The app itself sets lastModifiedBy to its own name.
        "resaved_by_another": bool(
            last_modified_by and last_modified_by != creator
        ),
        "created": _iso(created),
        "modified": _iso(modified),
        "rewritten_after_seconds": (
            int((modified - created).total_seconds())
            if created and modified else None
        ),
        "structural_damage": structural_damage(paragraphs),
        "sections": sections,
    }


def explain_empty_extraction_docx(path: str | Path) -> str:
    """Plain-English reason a .docx extraction came back empty.

    Structure only, like everything above — safe to print, paste or log.
    """
    d = diagnose_docx(path)

    if not d.get("readable"):
        return (
            "This file could not be read as a Word document at all.\n"
            f"(Technical reason: {d.get('failure', 'unknown')}.)\n\n"
            "The Collator's own download is a valid .docx, so this happened to\n"
            "the file after the app saved it — an upload, a mail gateway, or a\n"
            "rename of something that was never a Word file.\n\n"
            "Fix: ask for the file exactly as the app saved it —\n"
            "Uplift_Justification-<matter>.docx, straight from the browser's\n"
            "Downloads folder, before it was filed, uploaded or forwarded."
        )

    if d.get("structural_damage"):
        problems = "\n".join(f"  - {p}" for p in d["structural_damage"])
        return (
            "This document's section structure cannot be trusted, so nothing "
            "was read from it:\n\n"
            f"{problems}\n\n"
            "The Collator writes each section heading exactly once, in a fixed "
            "order,\nso this shape can only come from the document being edited "
            "after it was\ndownloaded. Reading around that would risk taking a "
            "pasted copy of a\nsection for the real one.\n\n"
            "Fix: re-download the summary from the app and send it on without "
            "editing it."
        )

    matched = {n for n, s in d["sections"].items() if s.get("matched")}
    ticks = sum(
        d["sections"][n].get("bullet_lines", 0)
        for n in ("stage1", "stage2")
        if n in matched
    )

    if not matched:
        note = ""
        if not d.get("made_by_the_app"):
            # The creator's name is deliberately not echoed: in a foreign
            # document it is usually a person, and this text gets pasted into
            # messages. Saying it is not the app's own stamp is enough.
            note = (
                "\nThe document does not name the Uplift Collator as its "
                "creator, so it\nwas made or rebuilt by something else.\n"
            )
        return (
            "This does not look like an Uplift Collator document.\n"
            f"It has text ({d['raw_chars']} characters in {d['paragraphs']} "
            "paragraphs) but none of\n"
            "the section headings the Collator writes — CASE DETAILS, PANEL\n"
            "MEMBERSHIP, STAGE 1, STAGE 2, PROPOSED UPLIFT.\n"
            + note +
            "\nFix: re-download it from the app's own \"Download Word Summary\" "
            "button."
        )

    if {"stage1", "stage2"} & matched and ticks == 0:
        return (
            "This is an Uplift Collator document, but no criteria were ticked "
            "in it.\nStage 1 and Stage 2 are both empty, so there is nothing to "
            "justify\nand no narrative to write.\n\n"
            "Fix: the solicitor needs to complete the questionnaire — tick the\n"
            "criteria that apply and give each one an explanation — then\n"
            "download it again."
        )

    if not {"stage1", "stage2"} & matched:
        return (
            "This document has Collator sections but no Stage 1 or Stage 2 "
            "section.\nFound: " + ", ".join(sorted(matched)) + ".\n\n"
            "That usually means it was edited after download, or generated by "
            "a\ndifferent version of the app.\n\n"
            "Fix: re-download it from the current app."
        )

    return (
        f"The Stage sections were found and contain {ticks} ticked item(s), "
        "but\nnone of their labels matched the current questionnaire, so "
        "nothing\ncould be recovered. Look for the unmatched-label report "
        "above.\n\n"
        "That means the document was generated against an older version of\n"
        "content-data.js whose wording has since changed, or its labels were\n"
        "edited after download.\n\n"
        "Fix: re-download it from the current app, without editing the labels."
    )
