"""Extract solicitor answers from a PDF generated by the Uplift Collator web app.

The PDF structure is produced by ``generatePdfSummary`` in ``script.js`` via
helpers ``addSectionHeader`` (renders UPPERCASE titles), ``addDetail`` (renders
``Label:  Value``) and ``addCriterion`` (renders three lines per ticked item:
bullet+label, category, ``Explanation: ...``). We parse against that structure.

Output shape mirrors the in-app ``formData``::

    {
      "caseDetails": {"feeEarnerName": ..., "matterType": ..., "caseMatterName": ...,
                      "courtLevel": ...},
      "panelMembership": {key: {"checked": True, "label": ...}, ...},
      "stage1": {key: {"checked": True, "label": ..., "explanation": ...,
                       "categoryTitle": ...}, ...},
      "stage2": {...},
      "finalUpliftPercent": "75",
      "evidenceOnFileConfirmed": True
    }

Labels are mapped back to QUESTION_BLOCKS keys via the lookup in
``templates.label_to_key_lookup``. A ticked item whose label matches nothing is
**not** dropped: it is recorded under ``unrecognised`` so the caller can stop
the run. Skipping it would silently remove a factor the solicitor claimed, and
a narrative that is quietly missing an argument reads exactly like one that
never had it.
"""

from __future__ import annotations

import difflib
import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pdfplumber

from templates import label_to_key_lookup

# Section markers as they appear in the PDF — UPPERCASE per addSectionHeader.
SECTION_PATTERNS: dict[str, re.Pattern[str]] = {
    "case_details": re.compile(r"^CASE DETAILS\s*$", re.MULTILINE),
    "panel_membership": re.compile(r"^PANEL MEMBERSHIP\s*$", re.MULTILINE),
    "stage1": re.compile(r"^STAGE 1: THRESHOLD TEST SELECTIONS\s*$", re.MULTILINE),
    "stage2": re.compile(r"^STAGE 2: LEVEL OF ENHANCEMENT FACTORS\s*$", re.MULTILINE),
    "proposed_uplift": re.compile(r"^PROPOSED UPLIFT\s*$", re.MULTILINE),
    # Added in v1.11. Absent from every earlier PDF, which is handled rather
    # than guarded against: section_slice simply finds no match and the
    # confirmation reads as false.
    #
    # Unlike its neighbours this one requires its own first line to follow,
    # and that is deliberate. Every pattern here matches the *first* bare
    # heading anywhere in the document, so a solicitor who pastes working
    # notes containing a line reading EVIDENCE ON FILE into a Stage 2
    # explanation would otherwise end the Stage 2 section there — dropping
    # every criterion after it — and send the confirmation search to a heading
    # inside their own prose, where it would find no status line and report a
    # real confirmation as absent. Demanding the status line makes a heading in
    # prose simply not a section. The older patterns share the weakness and are
    # left alone for now: changing them would alter how PDFs already sitting in
    # live matters are read, which is not a change to make in passing.
    "evidence_on_file": re.compile(
        r"^EVIDENCE ON FILE\s*\n\s*Evidence on file:\s*(?:Not confirmed|Confirmed)\b",
        re.MULTILINE,
    ),
    "disclaimer": re.compile(r"^DISCLAIMER\s*$", re.MULTILINE),
}

# The confirmation itself, read as two independent statements that must agree.
#
# The status line alone is one word away from reversing its meaning: lose the
# "Not " from "Evidence on file: Not confirmed" — the kind of damage a PDF
# rebuilt in transit does — and a refusal reads as a confirmation. So the
# sentence beneath it has to agree before this is treated as confirmed. Two
# separate strings must survive intact, and they fail in opposite directions,
# which is what makes the pair worth more than either alone.
EVIDENCE_STATUS = re.compile(
    r"^EVIDENCE ON FILE\s*\n\s*Evidence on file:\s*(?P<status>Not confirmed|Confirmed)\b",
    re.MULTILINE,
)
# Whitespace-tolerant because jsPDF wraps this sentence at the column width and
# the break lands in a different place depending on the page.
EVIDENCE_CONFIRMED_SENTENCE = re.compile(
    r"The fee earner\s+confirms\s+that\s+evidence\s+supporting"
)

# Per-page footer stamped by addFooter — strip before parsing.
FOOTER_PATTERN = re.compile(
    r"CONFIDENTIAL\s+[—-]\s+FOR LAA SUBMISSION\s+Page\s+\d+\s+of\s+\d+\s+Woodruff Billing Ltd"
)

# Per-page header rendered by addHeader.
HEADER_PATTERN = re.compile(
    r"W\s*Woodruff Billing Ltd\.\s+LAA Uplift Enhancement\s*\|\s*Data Summary"
)


def read_pdf_text(pdf_path: Path) -> str:
    """Read all pages and concatenate their text."""
    parts: list[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(parts)


def normalise_text(text: str) -> str:
    """Strip per-page headers and footers; collapse excessive blank lines."""
    text = FOOTER_PATTERN.sub("", text)
    text = HEADER_PATTERN.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def section_slice(text: str, name: str) -> str:
    """Return the text of *name* section, ending at the next known section."""
    pat = SECTION_PATTERNS[name]
    m = pat.search(text)
    if not m:
        return ""
    start = m.end()
    next_starts = []
    for other_name, other_pat in SECTION_PATTERNS.items():
        if other_name == name:
            continue
        m2 = other_pat.search(text, start)
        if m2:
            next_starts.append(m2.start())
    end = min(next_starts) if next_starts else len(text)
    return text[start:end].strip()


# The four fields addDetail prints, in the order it prints them. That order
# is what makes a wrapped value readable at all — see extract_case_details.
_DETAIL_FIELDS: list[tuple[str, str]] = [
    ("feeEarnerName", r"^Fee Earner:\s+"),
    ("matterType", r"^Matter Type:\s+"),
    ("caseMatterName", r"^Case / Matter Name:\s+"),
    # Printed since v1.11 because it fixes the ceiling at 50% or 100% under
    # CAG 12.2. Nothing here computes with it — this tool proposes no figure —
    # but the person checking a narrative needs it beside the percentage
    # claimed, and a PDF from before v1.11 simply yields "".
    ("courtLevel", r"^Court:\s+"),
]


def extract_case_details(text: str) -> dict:
    """The four case-detail fields, each rejoined if the PDF wrapped it.

    Parsed in the order the PDF prints them, because that order is the only
    thing that makes a wrapped value unambiguous. A value running past the
    line width carries no continuation marker, so a matter name reading
    "In the High Court: Re X and Y" arrives as::

        Case / Matter Name:  In the High
        Court: Re X and Y
        Court:  High Court

    where the second line opens with the label of a real field and is not one.
    Reading each value as everything up to where the *next* field starts
    resolves it: the court is the **last** ``Court:`` line, since it is
    printed last and nothing follows it in this section, so everything above
    that belongs to the name.

    Treating any line that merely looks like a label as the end of a value
    instead truncated the name to "In the High" and made the court
    "Re X and Y". The case name becomes ``{ITEM_OF_WORK}`` in the narrative,
    so that went to the LAA as the identity of the case.
    """
    block = section_slice(text, "case_details")
    starts: dict[str, tuple[int, int]] = {}
    for key, pattern in _DETAIL_FIELDS:
        # The last match, not the first: only a continuation can imitate a
        # label, and a continuation always sits *above* the field it imitates,
        # because the fields are printed in a fixed order.
        matches = list(re.finditer(pattern, block, re.MULTILINE))
        if matches:
            starts[key] = (matches[-1].start(), matches[-1].end())

    fields: dict[str, str] = {}
    ordered = [key for key, _ in _DETAIL_FIELDS if key in starts]
    for position, key in enumerate(ordered):
        value_to = (
            starts[ordered[position + 1]][0]
            if position + 1 < len(ordered)
            else len(block)
        )
        fields[key] = " ".join(block[starts[key][1]:value_to].split())
    for key, _ in _DETAIL_FIELDS:
        fields.setdefault(key, "")
    return fields


# ── Ticked lines whose label matches nothing ──────────────────────────────
#
# Such a line is one of two things, and they need different handling. Usually
# it is a known label with damage in it — a PDF that has been OCR'd or rebuilt
# by another program comes back with a bracket read as a brace, or a space lost
# before a slash. Rarely it is a line of the solicitor's own prose that happened
# to start with a bullet.
#
# The difference matters for confidentiality as much as for diagnosis. A
# damaged label is a fixed string from content-data.js with noise in it and
# carries nothing about the case, so it can be shown in full. An unrelated line
# may be case text, so only its length is reported. Similarity decides which.
LABEL_MATCH_FLOOR = 0.60


def _nearest_label(label: str, known: list[str]) -> tuple[str, float]:
    """The closest known label, and how close it is on a 0–1 scale."""
    best, best_ratio = "", 0.0
    for candidate in known:
        ratio = difflib.SequenceMatcher(None, label, candidate).ratio()
        if ratio > best_ratio:
            best, best_ratio = candidate, ratio
    return best, best_ratio


def _first_difference(read: str, expected: str) -> str:
    """Where the read text first departs from the label it should have been."""
    for i, (a, b) in enumerate(zip(read, expected)):
        if a != b:
            return (
                f"first difference at character {i + 1}: "
                f"read {a!r}, expected {b!r}"
            )
    if len(read) == len(expected):
        return "no character differs"
    if len(read) < len(expected):
        return (
            f"text ends early at character {len(read) + 1}: "
            f"expected {expected[len(read)]!r}"
        )
    return (
        f"unexpected text from character {len(expected) + 1}: "
        f"read {read[len(expected)]!r}"
    )


def _unrecognised(
    section: str, label: str, known: list[str], **extra: str
) -> dict:
    """Record one unmatched line, with the known label it most resembles.

    ``nearest`` is left empty below :data:`LABEL_MATCH_FLOOR`: naming a
    "closest" label that shares only a third of its characters invites
    correcting a line that was never that criterion in the first place.
    """
    nearest, ratio = _nearest_label(label, known)
    record = {
        "section": section,
        "label": label,
        "nearest": nearest if ratio >= LABEL_MATCH_FLOOR else "",
        "similarity": round(ratio, 3),
    }
    record.update(extra)
    return record


def describe_unrecognised_criteria(items: list[dict]) -> str:
    """Plain-English report of ticked lines that matched no known label.

    Structure only, on the same terms as :func:`diagnose`: a read label is
    echoed only where it is demonstrably a damaged copy of a known one, and the
    explanation beneath it is never touched. Safe to print to a terminal, paste
    into a message, or keep in a log.
    """
    n = len(items)
    lines = [
        f"narrate: {n} ticked "
        + ("item" if n == 1 else "items")
        + " could not be matched to a criterion in content-data.js."
    ]
    for item in items:
        section = item.get("section", "?")
        label = item.get("label", "")
        nearest = item.get("nearest", "")
        lines.append("")
        if nearest:
            lines.append(f"  {section} — read:    {label!r}")
            lines.append(f"  {' ' * len(section)}   nearest: {nearest!r}")
            lines.append(f"  {' ' * len(section)}   {_first_difference(label, nearest)}")
        else:
            lines.append(
                f"  {section} — a bulleted line of {len(label)} characters "
                "matching no known label."
            )
            lines.append(
                f"  {' ' * len(section)}   Not shown: too unlike any criterion "
                "to rule out case text."
            )
    lines.append("")
    lines.append(
        "Nothing was guessed. A label misread this way came off the same text "
        "layer as\nthe explanation beneath it, so correcting the label alone "
        "would leave prose that\nis just as wrong but no longer visibly so — "
        "read both against the page before\naccepting either."
    )
    return "\n".join(lines)


def extract_panel(
    text: str, label_keys: dict[str, str], unmatched: list[dict] | None = None
) -> dict:
    block = section_slice(text, "panel_membership")
    if not block or "None selected." in block:
        return {}
    result: dict[str, dict] = {}
    known = list(label_keys)
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped.startswith("•"):
            continue
        label = stripped.lstrip("•").strip()
        key = label_keys.get(label)
        if not key:
            # A panel membership can be worth more on its own than every
            # other factor combined, so a tick lost here is not the lesser
            # problem. Same treatment as a criterion.
            if unmatched is None:
                print(f"narrate: unknown panel label {label!r}", file=sys.stderr)
            else:
                unmatched.append(_unrecognised("panelMembership", label, known))
            continue
        result[key] = {"checked": True, "label": label}
    return result


def _resolve_wrapped_label(
    lines: list[str], label_keys: dict[str, str]
) -> tuple[str, int]:
    """The label from a bullet chunk, rejoined if the PDF wrapped it.

    Returns the label and how many lines it occupied.

    jsPDF wraps at the column width and marks the continuation in no way at
    all, so a label longer than one line arrives as two. Reading only the
    first line then leaves a label that matches nothing, and since ``2ba3adb``
    an unmatched label stops the whole run — so one Stage 1 label being eleven
    characters too long was enough to halt the narrator on any case that
    ticked it, with the continuation swallowed into the category title.

    Joining is driven entirely by exact matches against ``content-data.js``:
    a candidate is accepted only where the joined text **is** a known label,
    so this cannot invent a criterion out of two unrelated lines. Reported as
    the first line alone when nothing matches, because joining a category line
    onto damaged text would only obscure the damage.

    That is not the same as damage always stopping the run, and the stronger
    claim was wrong: damage can turn one real label into a *different* real
    label. Drop the parenthetical from the legacy Stage 1 "Difficulty in
    taking instructions (client/witnesses)" and what is left is the current
    Stage 2 label word for word. Exact matching cannot see that, which is why
    ``extract_criteria`` also checks the key it gets belongs to the section it
    was reading.
    """
    label = lines[0].lstrip("•").strip()
    if label in label_keys:
        return label, 1
    joined = label
    for index in range(1, len(lines)):
        nxt = lines[index].strip()
        if not nxt or nxt.startswith("Explanation:"):
            break
        joined = f"{joined} {nxt}"
        if joined in label_keys:
            return joined, index + 1
    return label, 1


# Which key prefix belongs under which heading. content-data.js names every
# key for its stage, current and retired alike, so this needs no second list
# kept in step by hand.
_SECTION_KEY_PREFIXES = {"stage1": "s1_", "stage2": "s2_"}


def extract_criteria(
    text: str,
    section_name: str,
    label_keys: dict[str, str],
    unmatched: list[dict] | None = None,
) -> dict:
    """Parse Stage 1 or Stage 2 criteria. Each ticked item in the PDF is::

        •  <label, wrapped over as many lines as it needs>
        <categoryTitle>
        Explanation: <text, possibly wrapped over multiple lines>
    """
    block = section_slice(text, section_name)
    if not block:
        return {}
    first_line = block.split("\n", 1)[0]
    if "No Stage" in first_line and "selected" in first_line:
        return {}

    # Split into chunks each beginning with a bullet at start-of-line.
    chunks = re.split(r"\n(?=•\s)", "\n" + block)
    result: dict[str, dict] = {}
    known = list(label_keys)
    for chunk in chunks:
        chunk = chunk.strip()
        if not chunk.startswith("•"):
            continue
        lines = [ln.rstrip() for ln in chunk.splitlines()]
        label, label_lines = _resolve_wrapped_label(lines, label_keys)

        category_parts: list[str] = []
        explanation_parts: list[str] = []
        in_explanation = False
        for line in lines[label_lines:]:
            stripped = line.strip()
            if not in_explanation and stripped.startswith("Explanation:"):
                in_explanation = True
                explanation_parts.append(stripped[len("Explanation:") :].strip())
            elif in_explanation:
                if stripped:
                    explanation_parts.append(stripped)
            else:
                if stripped:
                    category_parts.append(stripped)

        category_title = " ".join(category_parts).strip()
        explanation = " ".join(explanation_parts).strip()
        key = label_keys.get(label)
        # A key from the wrong stage is treated as no key at all. Exact
        # matching stops a damaged label being repaired into something like
        # it, but not from *being* something else: drop the parenthetical from
        # the legacy Stage 1 "Difficulty in taking instructions
        # (client/witnesses)" and what is left is the current Stage 2 label
        # word for word. Accepting it would have filed a threshold factor as a
        # level factor — a claim under a heading the solicitor never wrote —
        # and reported a clean run. A label under the wrong heading means a
        # damaged document whatever it says, so it stops the run like any
        # other unmatched line.
        if key and not key.startswith(_SECTION_KEY_PREFIXES[section_name]):
            key = None
        if not key:
            if unmatched is None:
                print(
                    f"narrate: unknown criterion label in {section_name}: {label!r}",
                    file=sys.stderr,
                )
            else:
                # The category and explanation travel with the record so a
                # corrected label can be re-resolved from narrative-input.json
                # without re-reading the PDF. They stay out of every message.
                unmatched.append(
                    _unrecognised(
                        section_name,
                        label,
                        known,
                        categoryTitle=category_title,
                        explanation=explanation,
                    )
                )
            continue
        result[key] = {
            "checked": True,
            "label": label,
            "categoryTitle": category_title,
            "explanation": explanation,
        }
    return result


def extract_uplift_percent(text: str) -> str:
    block = section_slice(text, "proposed_uplift")
    m = re.search(r"Proposed Uplift Percentage:\s*([\d.]+)\s*%", block)
    return m.group(1) if m else ""


def extract_evidence_confirmation(text: str) -> bool:
    """Whether the fee earner confirmed that the case file holds the evidence.

    Read strictly, and defaulting to False in every doubtful case. The
    narrative sentence this gates is an assertion to the LAA about the state
    of a file none of us has seen, so it must trace to a tick the solicitor
    actually made. A PDF produced before v1.11 has no such line, was never
    asked the question, and correctly comes back False — as does a damaged
    line we cannot read with certainty. The cost of a false negative is one
    absent sentence; the cost of a false positive is an unsupported assertion
    in a document going to the LAA under the solicitor's name.

    Both the status line and the sentence below it must say the same thing.
    See :data:`EVIDENCE_STATUS` for why one of them is not enough.

    The **last** such block in the document is the real one. The genuine
    section is printed second from the end, with only the disclaimer after it,
    so anything resembling it earlier came from the solicitor's own prose —
    boilerplate or a previous summary pasted into an explanation. Reading the
    first would let a pasted "Confirmed" outrank a genuine "Not confirmed"
    below it, which is the one direction this must never fail in.
    """
    matches = list(EVIDENCE_STATUS.finditer(text))
    if not matches:
        return False
    m = matches[-1]
    if m.group("status") != "Confirmed":
        return False
    # Bounded: far enough to clear the sentence and its wrapping, not so far
    # that the disclaimer or a later page could supply it.
    return bool(EVIDENCE_CONFIRMED_SENTENCE.search(text[m.end():m.end() + 400]))


# Below this, whatever pdfplumber recovered is noise — a stray glyph, a
# whitespace artefact — not a text layer. Judging on ``== 0`` was too strict:
# the real case that prompted this returned exactly 1 character, so the
# no-text branch never fired and the reader got a message about missing
# section headings in a file that had no text to put headings in.
MIN_TEXT_CHARS = 100

# Enough vector objects to *be* the page rather than decorate it. A Collator
# PDF draws a handful of separator lines; text converted to outlines produces
# roughly one path per glyph, so thousands.
OUTLINE_VECTOR_THRESHOLD = 500

# What a given producer tells you about how the file travelled. The producer
# names the software, but the useful question for the person holding the PDF
# is what to ask the sender — so each note says who would have been driving.
PRODUCER_NOTES = (
    (re.compile(r"Aspose", re.IGNORECASE),
     "Aspose is a document-processing library that runs *inside* other\n"
     "software — a case- or document-management system, a portal upload, an\n"
     "e-bundling tool, or a mail gateway. Nobody opens it and uses it by\n"
     "hand, so a system did this automatically while the file was in transit.\n"
     "Worth finding out which one: it will do the same to every future case."),
    (re.compile(r"Microsoft.*Print\s*To\s*PDF", re.IGNORECASE),
     "That is Windows' own \"Microsoft Print to PDF\" printer, so the file was\n"
     "re-printed rather than sent as it was saved."),
    (re.compile(r"Acrobat|Distiller", re.IGNORECASE),
     "Adobe Acrobat re-saved this file. Its Advanced print settings hold a\n"
     "sticky \"Print as image\" checkbox that rasterises everything until it\n"
     "is turned off again."),
    (re.compile(r"Ghostscript", re.IGNORECASE),
     "Ghostscript re-writes PDFs inside many server-side tools and mail\n"
     "gateways, so this was almost certainly automatic rather than deliberate."),
    (re.compile(r"Word|Office", re.IGNORECASE),
     "This went through Microsoft Word or Office. The Collator has no Word\n"
     "export at all, so the PDF was opened in Word and re-saved."),
)


def _producer_note(producer: str) -> str:
    """Plain-English note about a known PDF producer, or "" if unrecognised."""
    for pattern, note in PRODUCER_NOTES:
        if pattern.search(producer):
            return note
    return ""


# ── When the file was rewritten ─────────────────────────────────────────────
# The producer says *what* rewrote the file; the gap between creation and
# modification says *when in its life*, which points at a different system.
# Rewritten seconds after it was generated means an automatic process caught it
# on the way out — a mail gateway, a portal upload, a sanitiser. Rewritten days
# later means it happened when somebody filed or forwarded it. Those are
# different places to go looking.
#
# PDF date syntax is ``D:YYYYMMDDHHmmSSOHH'mm'``, truncatable at any point, with
# the offset optionally ``Z`` or absent. jsPDF also wraps the value in literal
# quote characters, so strip those first.
_PDF_DATE = re.compile(
    r"D:(?P<year>\d{4})(?P<month>\d{2})?(?P<day>\d{2})?"
    r"(?P<hour>\d{2})?(?P<minute>\d{2})?(?P<second>\d{2})?"
    r"(?:(?P<sign>[+\-Z])(?P<tzhour>\d{2})?'?(?P<tzmin>\d{2})?'?)?"
)

_MONTHS = ("January", "February", "March", "April", "May", "June", "July",
           "August", "September", "October", "November", "December")


def _parse_pdf_date(value: str) -> datetime | None:
    """Parse a PDF date string, or return None if it is missing or malformed."""
    if not value:
        return None
    m = _PDF_DATE.search(str(value).strip().strip('"').strip("'"))
    if not m:
        return None
    try:
        parts = {
            "year": int(m.group("year")),
            "month": int(m.group("month") or 1),
            "day": int(m.group("day") or 1),
            "hour": int(m.group("hour") or 0),
            "minute": int(m.group("minute") or 0),
            "second": int(m.group("second") or 0),
        }
        sign = m.group("sign")
        if sign and sign != "Z":
            offset = timedelta(hours=int(m.group("tzhour") or 0),
                               minutes=int(m.group("tzmin") or 0))
            tz = timezone(-offset if sign == "-" else offset)
        else:
            tz = timezone.utc
        return datetime(**parts, tzinfo=tz)
    except ValueError:
        # A malformed date is a curiosity, not a failure — the caller still has
        # the producer, which is the more useful half of the answer.
        return None


def _format_uk_date(moment: datetime) -> str:
    """House format — ``27 April '26 at 10:57``. Day-month-year, always."""
    return (f"{moment.day} {_MONTHS[moment.month - 1]} "
            f"'{moment.strftime('%y')} at {moment.strftime('%H:%M')}")


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _rewrite_timing_note(created: datetime | None,
                         modified: datetime | None) -> str:
    """Plain-English note about when the file was rewritten, or ""."""
    if not (created and modified):
        return ""
    gap = (modified - created).total_seconds()
    if gap < 0:
        return ""
    if gap < 300:
        return (
            f"It was generated on {_format_uk_date(created)} and rewritten "
            f"{_plural(int(gap), 'second')} later.\n"
            "A gap that short means an automatic process caught it in transit —\n"
            "a mail gateway, a portal upload, or a file sanitiser — rather than\n"
            "somebody opening it and re-saving it by hand."
        )
    if gap < 86400:
        return (
            f"It was generated on {_format_uk_date(created)} and rewritten "
            f"{_plural(int(gap // 3600), 'hour')} later, the same day.\n"
            "That is consistent with it being rewritten when the file was filed\n"
            "or sent, rather than as it was generated."
        )
    return (
        f"It was generated on {_format_uk_date(created)} and not rewritten\n"
        f"until {_format_uk_date(modified)} — {_plural(int(gap // 86400), 'day')} "
        "later.\nSo this happened when the file was filed, uploaded or forwarded,\n"
        "well after it was saved. Look at what handles it at that point, not\n"
        "at how it leaves the browser."
    )


class NoDataExtracted(Exception):
    """The PDF yielded nothing worth narrating.

    Raised so the run stops at the PDF rather than building an empty skeleton,
    spending a model call on it, and reporting the resulting nonsense as a
    citation failure. The message is written for the person holding the PDF,
    and contains no client text.
    """


def extraction_is_empty(formdata: dict) -> bool:
    """True when no Stage 1 or Stage 2 criterion was recovered.

    Panel membership and the uplift percentage are not enough on their own —
    the criteria *are* the narrative. A submission with neither has nothing to
    justify, so there is nothing to write.
    """
    return not (formdata.get("stage1") or formdata.get("stage2"))


def explain_empty_extraction(pdf_path: str | Path) -> str:
    """Plain-English reason an extraction came back empty.

    Built from :func:`diagnose`, so it reports structure only — never a field
    value, an explanation, or any other client text. Safe to print to a
    terminal, paste into a message, or write into a log.
    """
    d = diagnose(pdf_path)
    matched = {n for n, s in d["sections"].items() if s["matched"]}
    ticks = sum(
        s.get("bullet_lines", 0)
        for n, s in d["sections"].items()
        if n in ("stage1", "stage2")
    )

    made_by = d.get("producer") or d.get("creator") or ""
    timing = _rewrite_timing_note(
        datetime.fromisoformat(d["created"]) if d.get("created") else None,
        datetime.fromisoformat(d["modified"]) if d.get("modified") else None,
    )
    if d["raw_chars"] < MIN_TEXT_CHARS:
        # How the text was destroyed, which is not the same question as who
        # did it. Rasterised: the page became a picture. Outlined: each letter
        # became a drawing of its own shape — sharp at any zoom, and just as
        # unreadable. The two look identical on screen and need different
        # explanations, so the counts have to decide it, not a guess.
        rasterised = d.get("largest_image_page_coverage", 0) >= 0.5
        outlined = (
            not rasterised
            and d.get("images", 0) == 0
            and d.get("vector_objects", 0) >= OUTLINE_VECTOR_THRESHOLD
        )

        head = (
            "This PDF has no text in it — nothing can be read out of it.\n"
            "(That is also why you cannot select any text in it yourself.)\n"
        )

        if outlined:
            head += (
                f"\nThe pages are drawn as {d['vector_objects']} vector shapes with no\n"
                "text and no images. That means the text was converted to\n"
                "outlines: every letter turned into a drawing of its own shape.\n"
                "It still looks crisp at any zoom — which is why it does not\n"
                "look like a scan — but to software it is line art, not words.\n"
            )
        elif rasterised:
            head += (
                "\nThe page content is one large image, so this is a flattened\n"
                "copy — a picture of the page — rather than a scan of paper.\n"
            )

        if made_by:
            head += f"\nThe file says it was last written by: {made_by}\n"
            note = _producer_note(made_by)
            if note:
                head += f"\n{note}\n"

        if timing:
            head += f"\n{timing}\n"

        return head + (
            "\nThe Collator's own PDF always has selectable text, so this\n"
            "happened to the file *after* the app saved it — it is not\n"
            "something the solicitor did wrong in the app.\n\n"
            "Fix: ask for the file exactly as the app saved it —\n"
            "LAA_Uplift_Data_Summary.pdf, straight from the browser's Downloads\n"
            "folder, before it was filed, uploaded or forwarded anywhere.\n\n"
            "Do not re-key or OCR this copy: on an audited claim a mis-read page\n"
            "count or percentage is worse than no narrative at all. If the\n"
            "original is truly gone, re-enter the answers in the web app from\n"
            "this one and generate a fresh PDF."
        )

    if not d.get("made_by_the_app", True) and made_by:
        note = _producer_note(made_by)
        return (
            "This PDF has text, but none of the Collator's section headings —\n"
            "CASE DETAILS, PANEL MEMBERSHIP, STAGE 1, STAGE 2, PROPOSED UPLIFT.\n\n"
            f"It says it was written by: {made_by}\n"
            "The Collator writes its PDFs with jsPDF, so this file was made or\n"
            "rebuilt by something else.\n"
            + (f"\n{note}\n" if note else "")
            + (f"\n{timing}\n" if timing else "")
            + "\nFix: ask for the file the app itself saved —\n"
            "LAA_Uplift_Data_Summary.pdf, straight from the Downloads folder."
        )

    if not matched:
        return (
            "This does not look like an Uplift Collator PDF.\n"
            f"It has text ({d['raw_chars']} characters over {d['pages']} page(s)) but\n"
            "none of the section headings the Collator writes — CASE DETAILS,\n"
            "PANEL MEMBERSHIP, STAGE 1, STAGE 2, PROPOSED UPLIFT.\n\n"
            "The two usual causes:\n"
            "  - The browser's own Print-to-PDF was used instead of the app's\n"
            '    "Generate PDF Summary" button. Printing captures the on-screen\n'
            "    page, which has none of this structure.\n"
            "  - The PDF came from a different document altogether.\n\n"
            "Fix: re-generate it from the app's own button."
        )

    if {"stage1", "stage2"} & matched and ticks == 0:
        return (
            "This is an Uplift Collator PDF, but no criteria were ticked in it.\n"
            "Stage 1 and Stage 2 are both empty, so there is nothing to justify\n"
            "and no narrative to write.\n\n"
            "Fix: the solicitor needs to complete the questionnaire — tick the\n"
            "criteria that apply and give each one an explanation — then\n"
            "re-generate the PDF."
        )

    if not {"stage1", "stage2"} & matched:
        return (
            "This PDF has Collator sections but no Stage 1 or Stage 2 section.\n"
            f"Found: {', '.join(sorted(matched))}.\n\n"
            "That usually means it was generated by an older version of the web\n"
            "app whose headings differ.\n\n"
            "Fix: re-generate the PDF from the current app."
        )

    return (
        f"The Stage sections were found and contain {ticks} ticked item(s), but\n"
        "none of their labels matched the current questionnaire, so nothing\n"
        "could be recovered. Look for 'unknown criterion label' lines above.\n\n"
        "That means the PDF was generated against an older version of\n"
        "content-data.js whose wording has since changed.\n\n"
        "Fix: re-generate the PDF from the current app."
    )


def extract_formdata(pdf_path: str | Path) -> dict:
    """Read a Collator-generated PDF and return its formData equivalent."""
    pdf_path = Path(pdf_path)
    raw = read_pdf_text(pdf_path)
    text = normalise_text(raw)
    label_keys = label_to_key_lookup()
    unmatched: list[dict] = []
    data = {
        "caseDetails": extract_case_details(text),
        "panelMembership": extract_panel(text, label_keys, unmatched),
        "stage1": extract_criteria(text, "stage1", label_keys, unmatched),
        "stage2": extract_criteria(text, "stage2", label_keys, unmatched),
        "finalUpliftPercent": extract_uplift_percent(text),
        "evidenceOnFileConfirmed": extract_evidence_confirmation(text),
    }
    if unmatched:
        data["unrecognised"] = unmatched
    return data


def load_formdata_json(path: str | Path) -> dict:
    """Re-read a ``narrative-input.json``, re-resolving any corrected labels.

    The way out of an unmatched-label stop: fix the label in that file and run
    again. Every entry under ``unrecognised`` is looked up afresh, and any that
    now matches moves into its real section with its explanation intact. What
    still does not match stays put, so the run stops again rather than
    proceeding with the factor quietly missing.

    Re-resolving against ``content-data.js`` rather than trusting the file is
    the point: a hand-edited label is only accepted if it is now *exactly* a
    real criterion, so a near-miss correction cannot slip through.
    """
    path = Path(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path.name} does not contain a formData object.")
    for section in ("caseDetails", "panelMembership", "stage1", "stage2"):
        if not isinstance(data.get(section, {}), dict):
            raise ValueError(f"{path.name}: {section!r} is not an object.")

    label_keys = label_to_key_lookup()
    known = list(label_keys)
    still_unmatched: list[dict] = []
    for item in data.get("unrecognised") or []:
        label = (item.get("label") or "").strip()
        section = item.get("section", "")
        key = label_keys.get(label)
        if not key or section not in ("panelMembership", "stage1", "stage2"):
            still_unmatched.append(
                _unrecognised(
                    section or "?",
                    label,
                    known,
                    **{
                        k: item[k]
                        for k in ("categoryTitle", "explanation")
                        if k in item
                    },
                )
            )
            continue
        entry = {"checked": True, "label": label}
        if section != "panelMembership":
            entry["categoryTitle"] = item.get("categoryTitle", "")
            entry["explanation"] = item.get("explanation", "")
        data.setdefault(section, {})[key] = entry

    if still_unmatched:
        data["unrecognised"] = still_unmatched
    else:
        data.pop("unrecognised", None)
    return data


# PDF producers that mean "this file was rebuilt by something after the app
# made it". jsPDF is the only one the Collator itself ever writes.
JSPDF_PRODUCER = re.compile(r"jsPDF", re.IGNORECASE)


def diagnose(pdf_path: str | Path) -> dict:
    """Structural diagnostics for an extraction failure.

    Returns *only* shape/structure information — no raw text, no
    explanations, no field values — so the output is safe to share
    even when the input PDF contains GDPR-sensitive client data.

    ``producer``/``creator`` are the PDF's own software-name metadata, which
    names whatever last wrote the file. ``created``/``modified`` are its
    timestamps. Deliberately *only* those four: Title, Author, Subject and
    Keywords can carry a client name, so they are never read, and a timestamp
    identifies nobody. The software names distinguish "the app made this" from
    "something rebuilt it afterwards"; the timestamps say how long after
    generation that happened, which points at a different system again — an
    automatic pipeline on the way out, or something that ran when the file was
    later filed or forwarded.
    """
    pdf_path = Path(pdf_path)
    with pdfplumber.open(pdf_path) as pdf:
        n_pages = len(pdf.pages)
        per_page_chars = [len(p.extract_text() or "") for p in pdf.pages]
        meta = pdf.metadata or {}
        producer = str(meta.get("Producer", "") or "")
        creator = str(meta.get("Creator", "") or "")
        created = _parse_pdf_date(meta.get("CreationDate", ""))
        modified = _parse_pdf_date(meta.get("ModDate", ""))
        # Is the page a picture of itself? A flattened PDF has no characters
        # and one large image; a normal one has characters and no image.
        n_images = 0
        image_coverage = 0.0
        n_vectors = 0
        for page in pdf.pages:
            n_images += len(page.images)
            n_vectors += len(page.curves) + len(page.rects)
            page_area = float(page.width) * float(page.height)
            for img in page.images:
                if page_area <= 0:
                    continue
                area = (abs(float(img["x1"]) - float(img["x0"]))
                        * abs(float(img["bottom"]) - float(img["top"])))
                image_coverage = max(image_coverage, area / page_area)
    raw = read_pdf_text(pdf_path)
    text = normalise_text(raw)

    # Per-section presence and shape
    sections: dict[str, dict] = {}
    for name in SECTION_PATTERNS:
        m = SECTION_PATTERNS[name].search(text)
        if not m:
            sections[name] = {"matched": False}
            continue
        block = section_slice(text, name)
        lines = block.splitlines()
        bullet_lines = sum(1 for ln in lines if ln.lstrip().startswith("•"))
        explanation_markers = sum(
            1 for ln in lines if ln.lstrip().startswith("Explanation:")
        )
        sections[name] = {
            "matched": True,
            "start_offset": m.start(),
            "block_chars": len(block),
            "block_lines": len(lines),
            "bullet_lines": bullet_lines,
            "explanation_markers": explanation_markers,
        }

    return {
        "pdf": pdf_path.name,
        "pages": n_pages,
        "per_page_chars": per_page_chars,
        "raw_chars": len(raw),
        "normalised_chars": len(text),
        "header_matches": len(HEADER_PATTERN.findall(raw)),
        "footer_matches": len(FOOTER_PATTERN.findall(raw)),
        "producer": producer,
        "creator": creator,
        "created": created.isoformat() if created else "",
        "modified": modified.isoformat() if modified else "",
        # None when either timestamp is missing — which is itself informative:
        # the Collator's own PDFs carry a CreationDate and no ModDate, so a
        # ModDate appearing at all means something rewrote the file.
        "rewritten_after_seconds": (
            int((modified - created).total_seconds())
            if created and modified else None
        ),
        "made_by_the_app": bool(JSPDF_PRODUCER.search(producer)),
        "images": n_images,
        "largest_image_page_coverage": round(image_coverage, 3),
        "vector_objects": n_vectors,
        "sections": sections,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 3 or (
        len(sys.argv) == 3 and sys.argv[1] != "--debug"
    ):
        print(f"Usage: {sys.argv[0]} [--debug] <pdf_path>", file=sys.stderr)
        sys.exit(1)
    if len(sys.argv) == 3:
        out = diagnose(sys.argv[2])
    else:
        out = extract_formdata(sys.argv[1])
    print(json.dumps(out, indent=2, ensure_ascii=False))
